"""initial

Revision ID: 1e5ae206efac
Revises:
Create Date: 2026-05-17 11:52:44.491876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1e5ae206efac"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sport_types",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.bulk_insert(
        sa.table("sport_types", sa.column("code", sa.String)),
        [{"code": "NBA"}, {"code": "NFL"}, {"code": "MLB"}, {"code": "NCAA"}],
    )
    op.create_table(
        "players",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sport", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["sport"],
            ["sport_types.code"],
        ),
        sa.PrimaryKeyConstraint("id", "sport"),
    )
    op.create_table(
        "advanced_stats",
        sa.Column("player_id", sa.String(length=20), nullable=False),
        sa.Column("player_sport", sa.String(length=20), nullable=False),
        sa.Column("ws", sa.Float(), nullable=True),
        sa.Column("ws_48", sa.Float(), nullable=True),
        sa.Column("bpm", sa.Float(), nullable=True),
        sa.Column("vorp", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id", "player_sport"],
            ["players.id", "players.sport"],
        ),
        sa.PrimaryKeyConstraint("player_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("advanced_stats")
    op.drop_table("players")
    op.drop_table("sport_types")
    # ### end Alembic commands ###
