"""initial

Revision ID: 319dcfae4f6f
Revises:
Create Date: 2026-05-17 12:41:19.248073

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "319dcfae4f6f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA nba")
    op.create_table(
        "players",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("draft_year", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="nba",
    )
    op.create_table(
        "career_stats",
        sa.Column("player_id", sa.String(length=20), nullable=False),
        sa.Column("ws", sa.Float(), nullable=True),
        sa.Column("ws_48", sa.Float(), nullable=True),
        sa.Column("bpm", sa.Float(), nullable=True),
        sa.Column("vorp", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["nba.players.id"],
        ),
        sa.PrimaryKeyConstraint("player_id"),
        schema="nba",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("career_stats", schema="nba")
    op.drop_table("players", schema="nba")
    op.execute("DROP SCHEMA nba")
    # ### end Alembic commands ###
